Dashboard_Website/myapp/urls.py
from django.conf.urls import url
from myapp import views

urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^hashtags/$', views.hashtags, name='hashtags'),
	url(r'^hashtags/hashtag_usage_getter/$', views.hashtag_usage_getter, name='hashtag_usage_getter'),
	url(r'^hashtags/hashtag_top10_getter/$', views.hashtag_top10_getter, name='hashtag_top10_getter'),
	url(r'^hashtags/hashtag_sentiment_getter/$', views.hashtag_sentiment_getter, name='hashtag_sentiment_getter'),

	# to delete
	url(r"^create_metric/",views.query_creator,name="create_metric"),
	url(r"^create_neo4j_query_handler/$",views.create_neo4j_query_handler,name="create_neo4j_query_handler"),
	url(r"^create_mongo_query_handler/$",views.create_mongo_query_handler,name="create_mongo_query_handler"),
	url(r"^create_postprocessing_handler/$",views.create_postprocessing_handler,name="create_postprocessing_handler"),
	url(r"^create_custom_metric_handler/$", views.create_custom_metric_handler, name="create_custom_metric_handler"),

	url(r"^view_query_handler/$", views.view_query_handler, name="view_query_handler"),
	url(r"^delete_query_handler/$", views.delete_query_handler, name="delete_query_handler"),
	url(r"^view_post_proc_handler/$", views.view_post_proc_handler, name="view_post_proc_handler"),
	url(r"^delete_post_proc_handler/$", views.delete_post_proc_handler, name="delete_post_proc_handler"),

	url(r"^alerts/$", views.alerts, name="alerts"),
	url(r"^alerts/alerts_view", views.alerts_view, name="alerts_view"),
	url(r"^alerts/alerts_delete", views.alerts_delete, name="alerts_delete"),
	url(r"^alerts/alerts_activate", views.alerts_activate, name="alerts_activate"),
	url(r"^alerts/alerts_deactivate", views.alerts_deactivate, name="alerts_deactivate"),
	url(r"^alerts/alerts_tweets", views.alerts_tweets, name="alerts_tweets"),
	url(r"^alerts/alerts_dismiss", views.alerts_dismiss, name="alerts_dismiss"),
	url(r"^alerts/alerts_create_handler", views.alerts_create_handler, name="alerts_create_handler"),

	url(r"^create_query/$", views.query_creator, name="create_query"),

	url(r"^create_query/create_neo4j_query_handler/$",views.create_neo4j_query_handler,name="create_neo4j_query_handler"),
	url(r"^create_query/delete_all_variables_handler/$",views.delete_all_variables_handler,name="delete_all_variables_handler"),
	url(r"^create_query/create_mongo_query_handler/$",views.create_mongo_query_handler,name="create_mongo_query_handler"),
	url(r"^create_query/create_postprocessing_handler/$",views.create_postprocessing_handler,name="create_postprocessing_handler"),
	url(r"^create_query/delete_query_handler/(?P<query>[0-9a-zA-Z_-]+)$",views.delete_query_handler,name="delete_query_handler"),
	url(r"^create_query/view_custom_metric_handler/$", views.view_custom_metric_handler, name="view_custom_metric_handler"),

	url(r"^create_query/create_dag_handler", views.create_dag_handler, name ="create_dag_handler"),
	url(r"^create_query/view_dag_handler/(?P<dag_name>[0-9a-zA-Z_-]+)", views.view_dag_handler, name ="view_dag_handler"),
	url(r"^create_query/delete_dag_handler/(?P<dag_name>[0-9a-zA-Z_-]+)", views.delete_dag_handler, name ="delete_dag_handler"),

]

Dashboard_Website/myproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('myapp.urls'))
]

Dashboard_Website/myapp/models.py
from django.db import models
from django.utils.deconstruct import deconstructible
from django.contrib.auth.models import User
from datetime import datetime
# Create your models here.


class Tweet(models.Model):
	tname = models.CharField(max_length=200)
	hashtag = models.CharField(max_length=200)
	retweet_of = models.CharField(max_length=200)
	reply_of = models.CharField(max_length=200)
	quoted = models.CharField(max_length=200)
	has_mention = models.CharField(max_length=200)
	def __str__(self):
		return (self.tname)
class User(models.Model):
	uname = models.CharField(max_length=200)
	userid = models.CharField(max_length=200)
	username = models.CharField(max_length=200)
	userscreenname = models.CharField(max_length=200)

	def __str__(self):
		return (self.uname)

class Relation(models.Model):
	source = models.CharField(max_length=200)
	relation = models.CharField(max_length=200)
	destn = models.CharField(max_length=200)
	bt = models.CharField(max_length=200)
	et = models.CharField(max_length=200)

class Query(models.Model):
	name = models.CharField(max_length=50)
	query = models.TextField()
	type = models.CharField(max_length=50, choices=[(x,x) for x in ['neo4j','mongoDB','postProcesing']])

	def __str__(self):
		return self.name

# Delete this
class PostProcFunc(models.Model):
	name = models.CharField(max_length=50)
	code = models.TextField()

	def __str__(self):
		return self.name

# Delete this
class CustomMetric(models.Model):
	name = models.CharField(max_length=50)
	query = models.ForeignKey(Query,on_delete=models.CASCADE)
	post_proc = models.ForeignKey(PostProcFunc,on_delete=models.CASCADE)

	def __str__(self):
		return self.name

class QueryInput(models.Model):
	query = models.ForeignKey(Query,on_delete=models.CASCADE)
	input_name = models.CharField(max_length=50)
	attribute = models.CharField(max_length=50,default="_NOT_REQUIRED_")

	def __str__(self):
		return self.input_name
class QueryConstant(models.Model):
	query = models.ForeignKey(Query,on_delete=models.CASCADE)
	attribute = models.CharField(max_length=50)
	value = models.CharField(max_length=50)

	def __str__(self):
		return self.attribute+"="+self.value

class QueryOutput(models.Model):
	query = models.ForeignKey(Query,on_delete=models.CASCADE)
	output_name = models.CharField(max_length=50)

	def __str__(self):
		return self.output_name

class AlertSpecification(models.Model):
	alert_name = models.CharField(unique=True, max_length=50)
	filter = models.TextField(blank=True)
	keys = models.CharField(max_length=100, blank=True) # csv (0 or more) from ['user_id','hashtag','url','user_mention']
	window_length = models.IntegerField()
	window_slide = models.IntegerField()
	count_threshold = models.IntegerField()
	jar_path = models.TextField()
	flink_jar_id = models.TextField()
	current_job_id = models.TextField() # flink job id

class Dag(models.Model):
	source = models.TextField()
	dag_name = models.CharField(max_length=100, blank = False)
	description = models.TextField(default="No Description provided")
	dag_div = models.TextField()

	def __str__(self):
		return self.dag_name

Dashboard_Website/myapp/forms.py
from django import forms
# from django.forms.extras.widgets import SelectDateWidget
from material import *

from myapp.models import *

date_formats = ['%Y-%m-%dT%H:%M'] # this is returned by browsers implementing datetime-local
date_formats.extend([
 '%Y-%m-%d %H:%M:%S',    # '2006-10-25 14:30:59'
 '%Y-%m-%d %H:%M',       # '2006-10-25 14:30'
 '%Y-%m-%d',             # '2006-10-25'
 '%m/%d/%Y %H:%M:%S',    # '10/25/2006 14:30:59'
 '%m/%d/%Y %H:%M',       # '10/25/2006 14:30'
 '%m/%d/%Y',             # '10/25/2006'
 '%m/%d/%y %H:%M:%S',    # '10/25/06 14:30:59'
 '%m/%d/%y %H:%M',       # '10/25/06 14:30'
 '%m/%d/%y',             # '10/25/06' -- till here was the default django list, next are custom
 '%d/%m/%Y %H:%M',       # '25/10/2016 14:30'
 '%d-%m-%Y %H:%M']        # '25-10-2016 14:30'
)
# required for Tt2 = forms.DateTimeField(widget=forms.TextInput(attrs={'type': 'datetime-local','placeholder':'25/10/2018 14:30'}),input_formats=date_formats,required=False)

class HashtagForm(forms.Form):
	hashtag = forms.CharField(max_length = 50)
	start_time = forms.DateTimeField()
	end_time = forms.DateTimeField()

class Top10Form(forms.Form):
	start_time = forms.DateTimeField()
	end_time = forms.DateTimeField()

class UserForm(forms.Form):
	User_Variable  = forms.CharField(widget=forms.TextInput(attrs={'class' : 'myfieldclass'}),required=False)
	UserId = forms.CharField(widget=forms.TextInput(attrs={'class' : 'myfieldclass'}),required=False)
	User_Screen_Name = forms.CharField(widget=forms.TextInput(attrs={'class' : 'myfieldclass'}),required=False)

class TweetForm(forms.Form):
	Variable_Name  = forms.CharField(widget=forms.TextInput(attrs={'class' : 'myfieldclass'}),required=False)
	Hashtag  = forms.CharField(widget=forms.TextInput(attrs={'class' : 'myfieldclass'}),required=False)
	Retweet_Of = forms.ModelChoiceField(queryset=Tweet.objects.all(),required=False)
	Reply_Of = forms.ModelChoiceField(queryset=Tweet.objects.all(),required=False)
	Quoted = forms.ModelChoiceField(queryset=Tweet.objects.all(),required=False)
	Has_Mentioned = forms.ModelChoiceField(queryset=User.objects.all(),required=False)
	layout = Layout("Variable_Name","Hashtag",
					Row("Retweet_Of","Reply_Of"),
					Row("Quoted","Has_Mentioned"),
					)

class RelationForm(forms.Form):
	Source = forms.ModelChoiceField(queryset=User.objects.all(),required=False)
	URelationShip = forms.ChoiceField(choices=[(x,x) for x in [None,"FOLLOWS","STARTED_FOLLOWING","FOLLOWED"]],required=False,label='Type')
	UDestination = forms.ModelChoiceField(queryset=User.objects.all(),required=False,label='Destination')

	Ut1 = forms.DateTimeField(required=False,label='Begin Time')
	Ut2 = forms.DateTimeField(required=False,label='End Time')

	TRelationShip = forms.ChoiceField(choices=[(x,x) for x in [None,"TWEETED"]],required=False,label='Type')
	TDestination = forms.ModelChoiceField(queryset=Tweet.objects.all(),required=False,label='Destination')

	Tt1 = forms.DateTimeField(required=False,label='Begin Time')
	Tt2 = forms.DateTimeField(required=False,label='End Time')
	layout = Layout("Source",
					Fieldset("Choose the User Relationships",Row("URelationShip","UDestination"),Row("Ut1","Ut2")),
					Fieldset("Choose the Tweet Relationships",Row("TRelationShip","TDestination"),Row("Tt1","Tt2")),
					)

class EvaluateForm(forms.Form):
	Return_Variables  = forms.CharField(widget=forms.TextInput(attrs={'class' : 'myfieldclass'}))
	Query_Name = forms.CharField(widget=forms.TextInput(attrs={'class' : 'myfieldclass'}))

class PostProcForm(forms.Form):
	name = forms.CharField(max_length = 50)
	input_variable_names = forms.CharField(max_length=100)
	output_variable_names = forms.CharField(max_length=100)
	file = forms.FileField(required=False)

class CreateCustomMetricForm(forms.Form):
	# name = forms.CharField(max_length=50)
	DAG = forms.ModelChoiceField(queryset=Dag.objects.all())
	post_processing_function = forms.ModelChoiceField(queryset=Query.objects.filter(type="postProcessing"))
	input_arguments = forms.CharField(widget=forms.TextInput(attrs={'class' : 'myfieldclass'}))
	x_axis_output_field = forms.CharField(widget=forms.TextInput(attrs={'class' : 'myfieldclass'}))
	y_axis_output_field = forms.CharField(widget=forms.TextInput(attrs={'class' : 'myfieldclass'}))

	layout = Layout(Fieldset("Choose the DAG you want to execute",'DAG',
					Fieldset('Choose the Post Processing function to get plot values',
							 Row('post_processing_function', 'input_arguments'),
							 Row('x_axis_output_field', 'y_axis_output_field'))))

# class CustomMetricForm(forms.Form):
# 	metric = forms.ModelChoiceField(queryset=CustomMetric.objects.all())

class CreateAlertForm(forms.Form):
	# alert_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder':'No spaces allowed. Eg. viral_tweets'}))
	alert_name = forms.CharField(max_length=50, help_text='No spaces allowed. Eg. viral_tweets')
	filter = forms.CharField(required=False, widget=forms.Textarea,
		help_text='Eg. user_id.equals("i") && (hashtags.contains("h") || urls.contains("u") || user_mentions.contains("m"))')
	keys = forms.MultipleChoiceField(required=False, widget=forms.CheckboxSelectMultiple,
		choices=[('user_id','User Id'),('hashtag','Hashtag'),('url','URL'),('user_mention','User Mention')])
	window_length = forms.IntegerField(help_text='Window length in seconds')
	window_slide = forms.IntegerField(help_text='Window slide in seconds')
	count_threshold = forms.IntegerField(help_text='Alert threshold of tweets in above window')

	layout = Layout("alert_name", "filter", "keys", "window_length", "window_slide", "count_threshold")

# class CreateAlertForm(forms.ModelForm):
#     keys = forms.MultipleChoiceField(required=False, widget=forms.CheckboxSelectMultiple,
#         choices=[('user_id','User Id'),('hashtag','Hashtag'),('url','URL'),('user_mention','User Mention')])
#     class Meta:
#         model = AlertSpecification
#         fields = ['alert_name','filter','keys','window_length','window_slide','count_threshold']
#         help_texts = {
#             'alert_name':'NOTE: No spaces allowed. Eg. viral_tweets',
#             'filter':'Eg. user_id.equals("i") && (hashtags.contains("h") || urls.contains("u") || user_mentions.contains("m"))',
#             'window_length':'Window length in seconds',
#             'window_slide':'Window slide in seconds',
#             'count_threshold':'Alert threshold of tweets in above window'
#         }

class PopularHash(forms.Form):
	number = forms.CharField(widget=forms.TextInput(attrs={'class' : 'myfieldclass'}))
	query_name = forms.CharField(widget=forms.TextInput(attrs={'class' : 'myfieldclass'}))
	layout = Layout(Fieldset("Give the most popular hashtags in total","query_name","number"))

class PopularHashInInterval(forms.Form):
	number = forms.CharField(widget=forms.TextInput(attrs={'class' : 'myfieldclass'}))
	begin_time = forms.DateTimeField()
	end_time = forms.DateTimeField()
	query_name = forms.CharField(widget=forms.TextInput(attrs={'class' : 'myfieldclass'}))
	layout = Layout(Fieldset("Give the most popular hashtags in the time interval <Begin Time> and <End Time>",
							"query_name","number",
							 Row('begin_time', 'end_time')))

class HashUsageInInterval(forms.Form):
	hashtag  = forms.CharField(widget=forms.TextInput(attrs={'class' : 'myfieldclass'}),required=False)
	begin_time = forms.DateTimeField(required=False)
	end_time = forms.DateTimeField(required=False)
	query_name = forms.CharField(widget=forms.TextInput(attrs={'class' : 'myfieldclass'}),required=False)

	layout = Layout(Fieldset("Give the timetamps at which <hashtag> is used between <Begin Time> and <End Time>",
							"query_name",'hashtag',
							 Row('begin_time', 'end_time')))

class HashSentimentInInterval(forms.Form):
	hashtag  = forms.CharField(widget=forms.TextInput(attrs={'class' : 'myfieldclass'}),required=False)
	begin_time = forms.DateTimeField()
	end_time = forms.DateTimeField()
	query_name = forms.CharField(widget=forms.TextInput(attrs={'class' : 'myfieldclass'}),required=False)
	layout = Layout(Fieldset("Give the timetamps, associated positive and negative sentiment of a <hashtag> between <Begin Time> and <End Time>",
							"query_name",'hashtag',
							 Row('begin_time', 'end_time')))
class PopularUser(forms.Form):
	number = forms.CharField(widget=forms.TextInput(attrs={'class' : 'myfieldclass'}))
	query_name = forms.CharField(widget=forms.TextInput(attrs={'class' : 'myfieldclass'}))
	layout = Layout(Fieldset("Give the most popular users in total","query_name","number"))

class ViewDagForm(forms.Form):
	dag = forms.ModelChoiceField(queryset=Dag.objects.all())

class CreateDagForm(forms.Form):
	name = forms.CharField(max_length = 50)
	description = forms.CharField(widget=forms.Textarea,required=False)
	file = forms.FileField(required=False)

Dashboard_Website/templates/myapp/custom_metrics.html
{% extends "myapp/theme.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load render_table from django_tables2 %}

{% block head %}
<title>Custom Metrics</title>
{% endblock %}

{% block body %}

<div class="container-fluid">
	<ul class="nav nav-tabs">
	  <li class="active"><a data-toggle="tab" href="#create_neo4j_query">Create Neo4j Query</a></li>
	  <li><a data-toggle="tab" href="#create_mongo_query">Create MongoDB Query</a></li>
	  <li><a data-toggle="tab" href="#create_postprocessing">Create Post-Processing Function</a></li>
	  <li><a data-toggle="tab" href="#create_metric">Create Custom Metric</a></li>
	  <li><a data-toggle="tab" href="#view_metric">View Custom Metrics</a></li>
	</ul>

	<div class="tab-content">

		<div id="create_neo4j_query" class="tab-pane fade in active">
			<h3>Create Neo4j custom query</h3>
			{% include "myapp/neo4j_query.html" %}
		</div>

		<div id="create_mongo_query" class="tab-pane fade">
			<h3>Create MongoDB custom query</h3>
			{% include "myapp/mongo_query.html" %}
		</div>

		<div id="create_postprocessing" class="tab-pane fade">
			<h3>Create custom post-processing function</h3>
			<form id="uploadfileform" method="post" action="/create_postprocessing_handler/" enctype="multipart/form-data">{% csrf_token %}
			    {{ uploadfileform | crispy }}
			    <br>
			    <button type="submit" class="btn btn-primary">Submit!</button>
			</form>
		</div>

		<div id="create_metric" class="tab-pane fade">
			<h3>Create custom metric</h3>
			<form id="custommetricid" method="post" action="/create_custom_metric_handler/">{% csrf_token %}
			    {{ create_custom_metric_form | crispy }}
			    <br>
			    <button type="submit" class="btn btn-primary">Submit!</button>
			</form>
			<br><br>
			<a id="view_query_link" href="#">View selected query</a><br>
			<a id="delete_query_link" href="#">Delete selected query</a><br><br>
			<a id="view_post_proc_link" href="#">View selected post-processing function</a><br>
			<a id="delete_post_proc_link" href="#">Delete selected post-processing function</a>
		</div>

		<div id="view_metric" class="tab-pane fade">
			<h3>View custom metrics</h3>
			<form id="custom_metrics_form_id" method="post" action="/view_custom_metric_handler/">{% csrf_token %}
			    {{ custom_metrics_form | crispy }}
			    <br>
			    <button type="submit" class="btn btn-primary">Submit!</button>
			    <br>
			</form>
			<br>
			<button id="plot_graph" class="btn btn-success">Plot Graph!</button>
			<button id="create_table" class="btn btn-success">Create Table!</button>
			<br><br>
			<div id="custom_metric_space"></div>
		</div>

	</div>

</div>


<!-- Basic setup -->
<script type="text/javascript">
	$(function(){
	    $("#hashtags_tab").removeClass("active");
	    $("#mentions_tab").removeClass("active");
	    $("#urls_tab").removeClass("active");
	    $("#custom_metrics_tab").addClass("active");
	    $("#alerts_tab").removeClass("active");
	    $("#create_query_tab").removeClass("active");
	});
	var x_vals = [];
	var y_vals = [];
	var metric_name = "";
</script>

<!-- Plotting and creating table -->
<script type="text/javascript">
	function plot(x_, y_,title_,x_label,y_label,div_id) {
		var data = [{
			x: x_,
			y: y_,
			type: 'line'
		}];
		var layout = {
			title: title_,
			xaxis: {
				title: x_label,
				// showgrid: false,
				zeroline: false
			},
			yaxis: {
				title: y_label,
				// showline: false
			}
		};

		$("#"+div_id).html("");
		Plotly.newPlot(div_id, data, layout);	
	}

	function create_table(x_,y_,div_id) {
		trHTML = '<div class="col-sm-4"><ul class="list-group">';
    	$.each(x_, function (i, item) {
            trHTML += '<li class="list-group-item">' + x_[i] + '<span class="badge">' + y_[i].toString() + '</span></li>';
        });
    	trHTML += '</ul></div>';
    	$("#"+div_id).html(trHTML);
	}
</script>

<!-- On click kind of functions -->
<script type="text/javascript">
	$(document).ready(function() {

	    var frm = $('#custom_metrics_form_id');
	    frm.submit(function() {
	        $.ajax({
	            type: frm.attr('method'),
	            url: frm.attr('action'),
	            data: frm.serialize(),
	            success: function (data) {
	            	console.log(data);
	            	x_vals = data.x;
	            	y_vals = data.y;
	            	metric_name = $("#id_metric :selected").text();
	            	plot(x_vals, y_vals,'Result for metric: '+metric_name,'','','custom_metric_space');
	            },
	            error: function(data) {
	                $("#custom_metric_space").html("Something went wrong!");
	            }
	        });
	        return false;
	    });

	    $("#plot_graph").click(function(){
	        plot(x_vals, y_vals,'Result for metric: '+metric_name,'','','custom_metric_space');
	    });

	    $("#create_table").click(function(){
	        create_table(x_vals, y_vals,'custom_metric_space');
	    });

	    $("#view_query_link").on('click', function(){
	    	var newWindow = window.open();
	    	query_ = $("#id_query :selected").text();
	    	$.ajax({
	            type: "post",
	            url: "/view_query_handler/",
	            data: {query:query_},
	            success: function (data) {
	            	console.log(data);
	            	newWindow.document.write("<pre>"+data.query+"</pre>");
	            },
	            error: function(data) {
	            	newWindow.document.write("Something went wrong!");
	            }
	        });
	    	return true;
	    });

	    $("#delete_query_link").on('click', function(){
	    	query_ = $("#id_query :selected").text();
	    	$.post("/delete_query_handler/",
	            {query:query_},
	            function(data) {
	            	console.log(data);
	            	window.location.replace(data.url);
	            }
	        );
	    	return true;
	    });

	    $("#view_post_proc_link").on('click', function(){
	    	var newWindow = window.open();
	    	post_proc_ = $("#id_post_processing_function :selected").text();
	    	$.ajax({
	            type: "post",
	            url: "/view_post_proc_handler/",
	            data: {post_proc:post_proc_},
	            success: function (data) {
	            	console.log(data);
	            	newWindow.document.write("<pre>"+data.post_proc+"</pre>");
	            },
	            error: function(data) {
	            	newWindow.document.write("Something went wrong!");
	            }
	        });
	    	return true;
	    });

	    $("#delete_post_proc_link").on('click', function(){
	    	post_proc_ = $("#id_post_processing_function :selected").text();
	    	$.post("/delete_post_proc_handler/",
	            {post_proc:post_proc_},
	            function(data) {
	            	console.log(data);
	            	window.location.replace(data.url);
	            });
	    	return true;
	    });
	   
    });
</script>

{% endblock %}

Dashboard_Website/templates/myapp/mongo_query.html
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load render_table from django_tables2 %}
{% block body %}

<style type="text/css">
h4 {
   width: 100%;
   text-align: center;
   border-bottom: 1px solid #000;
   line-height: 0.1em;
   margin: 10px 0 20px;
}

h4 span {
    background:#fff;
    padding:0 10px;
}


</style>



<div class="container">
  <div class="row">
    <div class="jumbotron">

      <form  method='post' action="/create_mongo_query_handler/">{% csrf_token %}
        <h4><span>Most Popular hashtags</span></h4>
        <h5>Give the most popular hashtags in total</h5>
        {{ create_mongo_form_1|crispy }}
        <p class="bs-component">
            <center>
                <input class="btn btn-success btn-sm" type="submit" name="b1" value="Create" />
            </center>
        </p>
    </form>
        <p>&nbsp;</p>
        <p>&nbsp;</p>

    <form  method='post' action="/create_mongo_query_handler/">{% csrf_token %}
        <h4><span>Most popular hashtags in interval</span></h4>
        <h5>Give the most popular hashtags in the time interval &ltBegin Time&gt and &ltEnd Time&gt</h5>
        {{ create_mongo_form_2|crispy }}
        <p class="bs-component">
            <center>
                <input class="btn btn-success btn-sm" type="submit" name="b2" value="Create" />
            </center>
        </p>
    </form>
        <p>&nbsp;</p>
        <p>&nbsp;</p>

    <form  method='post' action="/create_mongo_query_handler/">{% csrf_token %}
        <h4><span>Usage of hashtag</span></h4>
        <h5>Give the timetamps at which &lthashtag&gt is used between &ltBegin Time&gt and &ltEnd Time&gt</h5>
        {{ create_mongo_form_3|crispy }}
        <p class="bs-component">
            <center>
                <input class="btn btn-success btn-sm" type="submit" name="b3" value="Create" />
            </center>
        </p>
    </form>
        <p>&nbsp;</p>
        <p>&nbsp;</p>

    <form  method='post' action="/create_mongo_query_handler/">{% csrf_token %}
        <h4><span>Usage and Sentiment of hashtag</span></h4>
        <h5>Give the timetamps, associated positive and negative sentiment of a &lthashtag&gt between &ltBegin Time&gt and &ltEnd Time&gt</h5>
        {{ create_mongo_form_4|crispy }}
        <p class="bs-component">
            <center>
                <input class="btn btn-success btn-sm" type="submit" name="b4" value="Create" />
            </center>
        </p>
    </form>
        <p>&nbsp;</p>
        <p>&nbsp;</p>

    </div>
  </div>
</div>
{% endblock %}

Dashboard_Website/templates/myapp/view_dag.html
{% load crispy_forms_tags %}

{% block head %}
<title>View DAG</title>
{% endblock %}

{% block body %}



<div id="viewdaginfo">
	<h3>View the DAG and its source</h3>
	<center>
	{{ dag.dag_div | safe }}
	</center>
	<br>
	<div>
	<pre>{{ dag.source }}</pre>
	</div>

</div>

{% endblock %}